# Upgrade packages using npm-check-updates, test, and create a PR if successful.
# Add an upgrade-packages script in your package.json, for ex:
#  "upgrade-packages": "ncu -u"

name: upgradebot

on:
  # Manual run from GitHub UI
  workflow_dispatch:
    inputs:
      upgradeBranchName:
        description: 'Branch to run updates in'
        required: true
        default: 'upgradebot'
      baseBranchName:
        description: 'Branch to merge upgrades into'
        required: true
        default: 'main'
  # Wednesdays at 1337
  #schedule:
  #  - cron: '37 13 * * 3'

permissions:
  pull-requests: write
  contents: write

jobs:
  upgrade-packages:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      # Suppresses annoying warning https://github.com/cypress-io/cypress/issues/15679
      TERM: xterm
      # Suppress Cypress installation progress messages
      CI: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Warning: Caching node_modules can't be used across node versions or with npm ci
    # ref: https://github.com/actions/cache/blob/main/examples.md#node---npm
    - name: Cache node_modules and Cypress
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          ~/.cache/Cypress
        key: node-${{ matrix.node-version }}-on-${{ runner.os }}-deps-${{ hashFiles('package-lock.json') }}

    - name: Install
      run: npm ci
    
    - name: Upgrade packages
      run: npm run upgrade-packages

    # Note: not npm ci, we want the lockfile to change
    - name: Install updates
      run: npm install

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm run test

    - name: Commit package.json updates
      uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081
      with:
        default_author: github_actions
        add: package.json package-lock.json
        message: "build(upgradebot): upgrade dependencies"
        # If no updates to both files, exit action
        pathspec_error_handling: exitImmediately
        new_branch: ${{ github.event.inputs.upgradeBranchName }}

    - name: Create package updates PR
      uses: actions/github-script@v6
      with:
        script: |
          console.log('Creating PR for dependencies upgrade');
          const head = '${{ github.event.inputs.upgradeBranchName }}' || 'upgradebot';
          const baseBranch = '${{ github.event.inputs.baseBranchName }}' || 'main';
          const body = '✅ This PR was created by UpgradeBot';
          await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'UpgradeBot',
            head: head,
            base: baseBranch,
            body: body
          });
